language: node_js
node_js: 10

notifications:
  email:
    recipients:
      - 875974254@qq.com
      - qinyuanpei@163.com
    on_success: change # default: change
    on_failure: always # default: always

install:
  - npm install --registry=https://registry.npm.taobao.org

script:
  # - npm run lint
  # - npm run test:ci
  #- npm run test:unit
  - npm run build:prod

after_script:
  - git config user.name "qinyuanpei"
  - git config user.email "qinyuanpei@163.com"
  - cd ./dist/
  - git init
  - git remote add origin master https://github.com/qinyuanpei/VisitorMapV.git
  - git add .
  - git commit -m "Update Blog By Travis-CI With Build $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:gh-pages

addons:
  apt:
    update: true

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/qinyuanpei/VisitorMapV
